use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use nesc_diagnostics::Diagnostic;

const MAIN_SOURCE: &str = r#"#include <nes.h>

NES_MAIN int main(void) {
    nes_wait_vblank();
    nes_set_background_color(0x21);

    while (true) {
        nes_wait_frame();
    }
}
"#;

/// Creates a new NesC project without overwriting an existing path.
///
/// # Errors
///
/// Returns a structured diagnostic when the name is invalid or a filesystem
/// operation fails.
pub fn create_project(name: &str, destination: &Path) -> Result<PathBuf, Box<Diagnostic>> {
    if !valid_project_name(name) {
        return Err(Box::new(
            Diagnostic::error("E0200", format!("invalid project name `{name}`"))
                .with_help("use ASCII letters, digits, `-`, or `_`, starting with a letter"),
        ));
    }

    if destination.exists() {
        return Err(Box::new(
            Diagnostic::error(
                "E0201",
                format!("destination `{}` already exists", destination.display()),
            )
            .with_help("choose a new destination; existing files are never overwritten"),
        ));
    }

    create_project_files(name, destination).map_err(|error| {
        cleanup_incomplete_project(destination);
        Box::new(Diagnostic::error(
            "E0202",
            format!(
                "could not create project at `{}`: {error}",
                destination.display()
            ),
        ))
    })?;

    Ok(destination.to_path_buf())
}

fn create_project_files(name: &str, destination: &Path) -> io::Result<()> {
    fs::create_dir(destination)?;
    fs::create_dir(destination.join("src"))?;
    fs::write(destination.join("NesC.toml"), manifest(name))?;
    fs::write(destination.join("src/main.c"), MAIN_SOURCE)?;
    fs::write(destination.join(".gitignore"), "/target\n")?;
    fs::write(
        destination.join("README.md"),
        format!("# {name}\n\nGenerated by `nesc new`.\n"),
    )?;
    Ok(())
}

fn cleanup_incomplete_project(destination: &Path) {
    if destination.is_dir() {
        let _ = fs::remove_dir_all(destination);
    }
}

fn manifest(name: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"

[build]
entry = "src/main.c"
assembly = []
region = "ntsc"
format = "nes2"

[cartridge]
mapper = 0
submapper = 0
mirroring = "horizontal"
prg-rom-kib = 32
chr-rom-kib = 8
battery = false

[compiler]
optimization = "size"
signed-overflow = "wrap"
bounds-checks = "elide-proven"
stack-limit = 192

[memory.zero-page]
available = ["0x00..0xEF"]
reserved = ["0xF0..0xFF"]
strategy = "frequency"

[debug]
symbols = true
source-map = true
"#
    )
}

fn valid_project_name(name: &str) -> bool {
    let mut characters = name.chars();
    characters
        .next()
        .is_some_and(|first| first.is_ascii_alphabetic())
        && characters
            .all(|character| character.is_ascii_alphanumeric() || matches!(character, '-' | '_'))
}

#[cfg(test)]
mod tests {
    use tempfile::tempdir;

    use crate::Project;

    use super::create_project;

    #[test]
    fn generated_project_loads() {
        let temporary = tempdir().expect("temporary directory");
        let destination = temporary.path().join("demo");
        create_project("demo", &destination).expect("project generation");

        let project = Project::load(destination.join("NesC.toml")).expect("valid project");
        assert_eq!(project.manifest().package.name, "demo");
        assert_eq!(project.entry_path(), destination.join("src/main.c"));
    }

    #[test]
    fn validates_chr_asset_manifest_rules() {
        let temporary = tempdir().expect("temporary directory");
        let destination = temporary.path().join("demo");
        create_project("demo", &destination).expect("project generation");
        let manifest_path = destination.join("NesC.toml");
        let base = std::fs::read_to_string(&manifest_path).expect("manifest source");

        std::fs::write(
            &manifest_path,
            format!("{base}\n[assets]\nchr = \"assets/tiles.chr\"\n"),
        )
        .expect("manifest with CHR asset");
        let project = Project::load(&manifest_path).expect("valid CHR manifest");
        assert_eq!(
            project.manifest().assets.chr.as_deref(),
            Some(std::path::Path::new("assets/tiles.chr"))
        );

        let chr_ram = base.replace("chr-rom-kib = 8", "chr-rom-kib = 0");
        std::fs::write(
            &manifest_path,
            format!("{chr_ram}\n[assets]\nchr = \"tiles.chr\"\n"),
        )
        .expect("CHR-RAM manifest");
        let errors = Project::load(&manifest_path).expect_err("CHR-RAM with assets.chr rejected");
        assert!(errors.iter().any(|error| error.code() == "E0113"));

        std::fs::write(
            &manifest_path,
            format!("{base}\n[assets]\nchr = \"../tiles.chr\"\n"),
        )
        .expect("escaping manifest");
        let errors = Project::load(&manifest_path).expect_err("escaping CHR path rejected");
        assert!(errors.iter().any(|error| error.code() == "E0113"));
    }

    #[test]
    fn does_not_overwrite_existing_destination() {
        let temporary = tempdir().expect("temporary directory");
        let error = create_project("demo", temporary.path()).expect_err("existing path rejected");
        assert_eq!(error.code(), "E0201");
    }
}
